language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - rustup component add clippy
script:
  - cargo clippy
  - cargo test
