language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
cache: cargo
before_script:
  - cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy
script:
  - cargo clippy
  - cargo test
