[package]
name = "toggl"
version = "0.1.0"
authors = ["Todd Hainsworth <hainsworth.todd@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = "0.9.9"
serde = "1.0.88"
serde_derive = "1.0.88"
serde_json = "1.0.38"
failure = "0.1.7"
